language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t dfarkas960/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dfarkas960/docker-react npm run test
